language: objective-c
os: osx
osx_image: xcode12
before_install:
  - echo -e "machine api.mapbox.com\n  login $SDK_REGISTRY_USER\n  password $SDK_REGISTRY_PASSWORD\n\n" > ~/.netrc
  - echo -e "machine mapbox.bintray.com\n  login $BINTRAY_USER\n  password $BINTRAY_PASSWORD" >> ~/.netrc
before_script: 
  - echo $MAPBOX_API_KEY > .mapbox
  - make dependencies
script:
  - xcodebuild -scheme Demo -destination platform\=iOS\ Simulator,name\=iPhone\ 11,OS\=latest clean test | xcpretty
after_script:
  - scripts/trigger_metrics.sh
branches:
  only:
  - develop
  - master
  - /^release/.*$/

before_deploy: xcodebuild -scheme "MapboxSearchUI" -destination platform=iOS\ Simulator,name=iPhone\ 11 clean test
deploy:
  provider: script
  script: bundle exec fastlane beta
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_EVENT_TYPE = "cron" || $TRAVIS_EVENT_TYPE = "api"
notifications:
  slack:
    rooms:
      - mapbox:rvYzCIzlDAan4aIsehoUxok6
      - mapbox:t5lJ1LCG6NeaVn35X7XcYOJl
    on_success: change
    on_failure: always
