comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes

coverage:
  status:
    project:
      default: # https://docs.codecov.com/docs/commit-status
        threshold: 1%
