# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
version: 2.1

workflows:
  version: 2
  documentation-build:
    jobs:
      - dummy

jobs:
  dummy:
    macos:
      xcode: 12.5.0
    steps:
      - run: echo "Hello World"